/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const AUTH_TOKEN_STORAGE_KEY: typeof import('./lib/auth.js').AUTH_TOKEN_STORAGE_KEY
  const EffectScope: typeof import('vue').EffectScope
  const clearAccessToken: typeof import('./lib/auth.js').clearAccessToken
  const computed: typeof import('vue').computed
  const contentBlocks: typeof import('./lib/siteHome.js').contentBlocks
  const contentHeading: typeof import('./lib/siteHome.js').contentHeading
  const createApp: typeof import('vue').createApp
  const createRequest: typeof import('./lib/index.js').createRequest
  const csvDownloadUrl: typeof import('./lib/csvFiles.js').csvDownloadUrl
  const customRef: typeof import('vue').customRef
  const defineAsyncComponent: typeof import('vue').defineAsyncComponent
  const defineComponent: typeof import('vue').defineComponent
  const deleteCsvFile: typeof import('./lib/csvFiles.js').deleteCsvFile
  const deleteSyncItem: typeof import('./lib/accountSync.js').deleteSyncItem
  const effectScope: typeof import('vue').effectScope
  const featureCards: typeof import('./lib/siteHome.js').featureCards
  const getAccessToken: typeof import('./lib/auth.js').getAccessToken
  const getCsvFile: typeof import('./lib/csvFiles.js').getCsvFile
  const getCsvRows: typeof import('./lib/csvFiles.js').getCsvRows
  const getCurrentInstance: typeof import('vue').getCurrentInstance
  const getCurrentScope: typeof import('vue').getCurrentScope
  const getCurrentUser: typeof import('./lib/auth.js').getCurrentUser
  const getCurrentWatcher: typeof import('vue').getCurrentWatcher
  const getSyncItem: typeof import('./lib/accountSync.js').getSyncItem
  const githubLoginUrl: typeof import('./lib/auth.js').githubLoginUrl
  const h: typeof import('vue').h
  const heroActions: typeof import('./lib/siteHome.js').heroActions
  const heroMetrics: typeof import('./lib/siteHome.js').heroMetrics
  const heroStacks: typeof import('./lib/siteHome.js').heroStacks
  const heroStatus: typeof import('./lib/siteHome.js').heroStatus
  const homeHero: typeof import('./lib/siteHome.js').homeHero
  const inject: typeof import('vue').inject
  const isProxy: typeof import('vue').isProxy
  const isReactive: typeof import('vue').isReactive
  const isReadonly: typeof import('vue').isReadonly
  const isRef: typeof import('vue').isRef
  const isShallow: typeof import('vue').isShallow
  const listCsvFiles: typeof import('./lib/csvFiles.js').listCsvFiles
  const listSyncItems: typeof import('./lib/accountSync.js').listSyncItems
  const logout: typeof import('./lib/auth.js').logout
  const markRaw: typeof import('vue').markRaw
  const nextTick: typeof import('vue').nextTick
  const onActivated: typeof import('vue').onActivated
  const onBeforeMount: typeof import('vue').onBeforeMount
  const onBeforeRouteLeave: typeof import('vue-router').onBeforeRouteLeave
  const onBeforeRouteUpdate: typeof import('vue-router').onBeforeRouteUpdate
  const onBeforeUnmount: typeof import('vue').onBeforeUnmount
  const onBeforeUpdate: typeof import('vue').onBeforeUpdate
  const onDeactivated: typeof import('vue').onDeactivated
  const onErrorCaptured: typeof import('vue').onErrorCaptured
  const onMounted: typeof import('vue').onMounted
  const onRenderTracked: typeof import('vue').onRenderTracked
  const onRenderTriggered: typeof import('vue').onRenderTriggered
  const onScopeDispose: typeof import('vue').onScopeDispose
  const onServerPrefetch: typeof import('vue').onServerPrefetch
  const onUnmounted: typeof import('vue').onUnmounted
  const onUpdated: typeof import('vue').onUpdated
  const onWatcherCleanup: typeof import('vue').onWatcherCleanup
  const primaryNavItems: typeof import('./lib/siteNavigation.js').primaryNavItems
  const provide: typeof import('vue').provide
  const reactive: typeof import('vue').reactive
  const readonly: typeof import('vue').readonly
  const ref: typeof import('vue').ref
  const request: typeof import('./lib/index.js').request
  const resolveComponent: typeof import('vue').resolveComponent
  const saveSyncItem: typeof import('./lib/accountSync.js').saveSyncItem
  const setAccessToken: typeof import('./lib/auth.js').setAccessToken
  const shallowReactive: typeof import('vue').shallowReactive
  const shallowReadonly: typeof import('vue').shallowReadonly
  const shallowRef: typeof import('vue').shallowRef
  const shellStatus: typeof import('./lib/siteNavigation.js').shellStatus
  const toRaw: typeof import('vue').toRaw
  const toRef: typeof import('vue').toRef
  const toRefs: typeof import('vue').toRefs
  const toValue: typeof import('vue').toValue
  const triggerRef: typeof import('vue').triggerRef
  const unref: typeof import('vue').unref
  const uploadCsvFile: typeof import('./lib/csvFiles.js').uploadCsvFile
  const useAttrs: typeof import('vue').useAttrs
  const useCssModule: typeof import('vue').useCssModule
  const useCssVars: typeof import('vue').useCssVars
  const useId: typeof import('vue').useId
  const useLink: typeof import('vue-router').useLink
  const useModel: typeof import('vue').useModel
  const useRoute: typeof import('vue-router').useRoute
  const useRouter: typeof import('vue-router').useRouter
  const useSlots: typeof import('vue').useSlots
  const useTemplateRef: typeof import('vue').useTemplateRef
  const watch: typeof import('vue').watch
  const watchEffect: typeof import('vue').watchEffect
  const watchPostEffect: typeof import('vue').watchPostEffect
  const watchSyncEffect: typeof import('vue').watchSyncEffect
  const workspaceNavItems: typeof import('./lib/siteNavigation.js').workspaceNavItems
}
// for type re-export
declare global {
  // @ts-ignore
  export type { Component, Slot, Slots, ComponentPublicInstance, ComputedRef, DirectiveBinding, ExtractDefaultPropTypes, ExtractPropTypes, ExtractPublicPropTypes, InjectionKey, PropType, Ref, ShallowRef, MaybeRef, MaybeRefOrGetter, VNode, WritableComputedRef } from 'vue'
  import('vue')
}
