/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AccountDeleteDialog: typeof import('./components/account/AccountDeleteDialog.vue')['default']
    AccountLinkResultDialog: typeof import('./components/account/AccountLinkResultDialog.vue')['default']
    AccountSyncPanel: typeof import('./components/tools/AccountSyncPanel.vue')['default']
    AuthAccountRow: typeof import('./components/account/AuthAccountRow.vue')['default']
    AuthProviderButton: typeof import('./components/site/AuthProviderButton.vue')['default']
    BindEmailDialog: typeof import('./components/account/BindEmailDialog.vue')['default']
    NarrativeSection: typeof import('./components/site/NarrativeSection.vue')['default']
    NumberedRow: typeof import('./components/site/NumberedRow.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SiteHeaderNavigation: typeof import('./components/site/SiteHeaderNavigation.vue')['default']
    SiteMobileNavigation: typeof import('./components/site/SiteMobileNavigation.vue')['default']
    SiteThemeSwitcher: typeof import('./components/site/SiteThemeSwitcher.vue')['default']
    SiteUserMenu: typeof import('./components/site/SiteUserMenu.vue')['default']
    ToolArchivePanel: typeof import('./components/tools/ToolArchivePanel.vue')['default']
    ToolPageHeader: typeof import('./components/tools/ToolPageHeader.vue')['default']
    ToolSaveDialog: typeof import('./components/tools/ToolSaveDialog.vue')['default']
    ToolSavePanel: typeof import('./components/tools/ToolSavePanel.vue')['default']
    ToolWorkbench: typeof import('./components/tools/ToolWorkbench.vue')['default']
    UAlert: typeof import('@nuxt/ui/components/Alert.vue')['default']
    UAvatar: typeof import('@nuxt/ui/components/Avatar.vue')['default']
    UBadge: typeof import('@nuxt/ui/components/Badge.vue')['default']
    UButton: typeof import('@nuxt/ui/components/Button.vue')['default']
    UCard: typeof import('@nuxt/ui/components/Card.vue')['default']
    UForm: typeof import('@nuxt/ui/components/Form.vue')['default']
    UFormField: typeof import('@nuxt/ui/components/FormField.vue')['default']
    UInput: typeof import('@nuxt/ui/components/Input.vue')['default']
    UModal: typeof import('@nuxt/ui/components/Modal.vue')['default']
    UPopover: typeof import('@nuxt/ui/components/Popover.vue')['default']
    USelect: typeof import('@nuxt/ui/components/Select.vue')['default']
    USlideover: typeof import('@nuxt/ui/components/Slideover.vue')['default']
    UTextarea: typeof import('@nuxt/ui/components/Textarea.vue')['default']
  }
}
